# Чеклист: что нужно знать про NumPy и pandas

**Курс «Машинное обучение», 4 курс. К занятию 1.**

Занятие 1 не требует теории машинного обучения — оно требует умения обращаться
с таблицей и массивом. Опыт у всех разный: кто-то писал на `pandas` курсовую,
кто-то видел его впервые. Этот файл нужен, чтобы **до** занятия стало понятно,
чего именно от вас ждут.

Список закрытый. Он собран по тому, что реально встречается в занятии 1 и в
домашней работе к нему, — поэтому короткий. Всего, чего здесь нет, на первом
занятии не понадобится: см. раздел «Чего знать не нужно» в конце.

## Как этим пользоваться

1. Пройдите оба списка и честно отметьте, что не знаете. Пункт засчитывается,
   если вы можете **написать строчку кода**, а не «где-то видели».
2. Дойдите до раздела «Проверьте себя» и решите задачи, не запуская код:
   сначала ответ в голове, потом `Shift+Enter`.
3. Если незнакомо больше трети пунктов — потратьте вечер на источники из
   последнего раздела. Это окупится: дальше все девять занятий написаны на
   этих же приёмах.

Незнание `numpy` и `pandas` — не проблема и не повод переживать. Проблема —
узнать об этом на паре.

---
## NumPy

Массив — это таблица чисел фиксированного типа. Всё, что нужно на занятии 1:

- [ ] **Массив и его форма.** `np.array([1, 2, 3])`, `X.shape`, `X.dtype`.
  Понимать, что `shape == (100, 5)` — это 100 объектов по 5 признаков.
- [ ] **Индексация и срезы по двум осям.** `X[0]` — первая строка,
  `X[:, 1]` — второй столбец целиком, `X[2:5, :2]` — кусок таблицы.
- [ ] **Булева маска.** `x[x > 0]` — отбор; `(x > 0).sum()` — сколько таких;
  `(x > 0).mean()` — **доля** таких. Последнее используется постоянно.
- [ ] **Аргумент `axis`.** `X.mean(axis=0)` — среднее по каждому столбцу
  (схлопываем строки), `axis=1` — по каждой строке. Путаница здесь —
  самая частая ошибка новичков.
- [ ] **Broadcasting.** `X - X.mean(axis=0)` вычитает из каждой строки вектор
  средних, без единого цикла. Понимать, почему формы `(100, 5)` и `(5,)`
  совместимы, а `(100, 5)` и `(100,)` — нет.
- [ ] **Матричное умножение и транспонирование.** `X.T @ X`, `X @ theta`.
  Знать, что `@` — это не `*`: `*` умножает поэлементно.
- [ ] **`np.nan`.** `np.nan != np.nan` — правда, поэтому пропуски ищут через
  `np.isnan(x)`, а не сравнением. Отсюда же `nan` заражает суммы и средние.
- [ ] **Воспроизводимость.** `rng = np.random.default_rng(42)`, потом
  `rng.normal(size=10)`. Один и тот же seed — один и тот же результат.
- [ ] **Векторизация вместо цикла.** Если вы пишете `for i in range(len(X))`,
  почти наверняка есть запись без цикла — короче и в десятки раз быстрее.
  Это единственный пункт, который занятие 1 разбирает специально: если он
  незнаком, ничего страшного.

---
## pandas

Таблица со столбцами разных типов и с именами. Нужно вот это:

- [ ] **`DataFrame` и `Series`.** Таблица и один её столбец. `df.shape`,
  `df.head()`, `df.dtypes`, `df.info()`.
- [ ] **Выбор столбца.** `df["age"]` — это `Series`, а `df[["age"]]` — это
  `DataFrame` из одного столбца. Разница всплывает при передаче в `sklearn`.
- [ ] **`.loc` и `.iloc`.** `df.loc[5, "age"]` — по имени, `df.iloc[5, 2]` —
  по номеру. Знать, что это разные вещи.
- [ ] **Фильтр по условию.** `df[df["age"] > 30]`; несколько условий —
  через `&`, `|` и **обязательные скобки**: `df[(df["age"] > 30) & (df["fare"] < 50)]`.
- [ ] **Пропуски.** `df.isna().sum()` — сколько в каждом столбце,
  `df.dropna()` — выбросить строки, `df["age"].fillna(значение)` — заполнить.
- [ ] **Преобразование значений.** `.astype(int)`, `.map({"yes": 1, "no": 0})`,
  `.replace(...)`, а для текста — `.str.replace(",", ".")` и `.str.strip()`.
- [ ] **Группировка.** `df.groupby("pclass")["survived"].mean()` — среднее по
  группам; `.agg(["size", "mean"])` — сразу несколько сводок.
- [ ] **Частоты и уникальные.** `.value_counts()`, `.nunique()`, `.unique()`,
  а для пары столбцов — `pd.crosstab(a, b, normalize="index")`.
- [ ] **Сводки.** `.describe()`, `.median()`, `.corr()`.
- [ ] **Дубликаты и типы столбцов.** `df.duplicated().sum()`,
  `df.select_dtypes(include="number")`.

---
## Проверьте себя

Восемь вопросов. Сначала ответьте, **не запуская** ячейку, потом запустите и
сверьтесь. Если сошлось семь-восемь — на занятии будет комфортно.

**NumPy.** Дано `X` формы `(4, 3)` и вектор `v` формы `(3,)`:

1. Какая форма у `X.mean(axis=0)`? А у `X.mean(axis=1)`?
2. Что делает `X - v` и почему это не ошибка?
3. Чему равно `(X > 5).mean()` — по смыслу, не по числу?
4. Какая форма у `X.T @ X`?

**pandas.** Дана таблица `df` со столбцами `группа` (A/B) и `балл`:

5. Чем `df["балл"]` отличается от `df[["балл"]]`?
6. Что вернёт `df[df["балл"] > 4]` и что — `(df["балл"] > 4).mean()`?
7. Что напечатает `df.groupby("группа")["балл"].mean()`?
8. Почему `df["балл"].isna().sum()` — это не то же самое, что `df["балл"].sum()`?

In [1]:
import numpy as np
import pandas as pd

X = np.arange(12).reshape(4, 3)          # 4 объекта, 3 признака
v = np.array([100, 200, 300])

print("X =\n", X)
print("\n1) X.mean(axis=0) =", X.mean(axis=0), "-> форма", X.mean(axis=0).shape)
print("   X.mean(axis=1) =", X.mean(axis=1), "-> форма", X.mean(axis=1).shape)
print("\n2) X - v =\n", X - v)
print("\n3) (X > 5).mean() =", (X > 5).mean())
print("\n4) X.T @ X -> форма", (X.T @ X).shape)

X =
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

1) X.mean(axis=0) = [4.5 5.5 6.5] -> форма (3,)
   X.mean(axis=1) = [ 1.  4.  7. 10.] -> форма (4,)

2) X - v =
 [[-100 -199 -298]
 [ -97 -196 -295]
 [ -94 -193 -292]
 [ -91 -190 -289]]

3) (X > 5).mean() = 0.5

4) X.T @ X -> форма (3, 3)


In [2]:
df = pd.DataFrame({"группа": ["A", "A", "B", "B", "B"],
                   "балл":   [5.0, 3.0, 4.0, np.nan, 2.0]})
display(df)

print("5) df['балл'] -- это", type(df["балл"]).__name__,
      "| df[['балл']] -- это", type(df[["балл"]]).__name__)

print("\n6) строк с баллом > 4:", len(df[df["балл"] > 4]),
      "| доля таких:", (df["балл"] > 4).mean())

print("\n7) среднее по группам:")
print(df.groupby("группа")["балл"].mean())

print("\n8) пропусков:", df["балл"].isna().sum(), "| сумма баллов:", df["балл"].sum())

,группа,балл
0,A,5.0
1,A,3.0
2,B,4.0
3,B,NaN
4,B,2.0


5) df['балл'] -- это Series | df[['балл']] -- это DataFrame

6) строк с баллом > 4: 1 | доля таких: 0.2

7) среднее по группам:
группа
A    4.0
B    3.0
Name: балл, dtype: float64

8) пропусков: 1 | сумма баллов: 14.0


### Ответы и что за ними стоит

1. `(3,)` и `(4,)`. `axis` — это ось, **вдоль которой схлопываем**: `axis=0`
   убирает строки и оставляет число на каждый столбец (среднее признака),
   `axis=1` убирает столбцы и даёт число на каждый объект.
2. Вычитает `v` из **каждой строки**. Формы `(4, 3)` и `(3,)` совместимы:
   NumPy мысленно растягивает вектор на все строки. Это broadcasting, и на
   нём держится вся стандартизация признаков.
3. Долю элементов, больших пяти. `(X > 5)` — массив из `True`/`False`,
   а среднее булева массива и есть доля истинных значений.
4. `(3, 3)`. Матрица $X^{\mathsf T}X$ размера «признаки на признаки» — она
   появится уже на занятии 2 и не исчезнет до конца курса.
5. Первое — `Series` (один столбец), второе — `DataFrame` (таблица из одного
   столбца). Разные типы, и `sklearn` к этому чувствителен.
6. Первое — **таблицу** из подходящих строк, второе — **число**, долю таких
   строк. Второе понадобится чаще, чем кажется.
7. Среднее по каждой группе: `A` — 4.0, `B` — 3.0. Обратите внимание: у `B`
   три строки, но одна с пропуском, и `mean` считает по двум. Молча.
8. `isna().sum()` считает, сколько значений **отсутствует** (здесь 1), а
   `sum()` складывает сами баллы, пропуск при этом пропуская (здесь 14.0).
   Разница между «нет данных» и «ноль» — то, с чего начинается занятие 1.

---
## Чего знать не нужно

Чтобы не тратить время на лишнее, вот что на первом занятии (и почти во всём
курсе) **не понадобится**:

* объединение таблиц — `merge`, `join`, `concat`;
* иерархические индексы (`MultiIndex`), `stack`, `unstack`, `pivot`;
* временные ряды, даты, часовые пояса, `resample`;
* `apply` со своей функцией по строкам — почти всегда это признак того, что
  задача решается векторно;
* `numba`, `cython`, ускорение кода;
* SQL и базы данных;
* глубокое знание `matplotlib` — на занятии 1 показывается `seaborn`, где
  график строится одной строкой.

Курс сознательно обходится базовым стеком: `numpy`, `pandas`, `matplotlib`,
`seaborn`, `scipy`, `scikit-learn`. Ничего больше устанавливать не нужно.

---
## Где восполнить пробелы

Официальные руководства — самые короткие из существующих и написаны как раз
для тех, кто видит библиотеку впервые. Оба на английском, но текста там мало,
а кода много.

* **NumPy** — [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html).
  Читать до раздела о broadcasting включительно; всё, что дальше, — по желанию.
* **pandas** — [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html).
  Нужны разделы Selection, Missing data, Operations, Grouping. Merge, Reshaping,
  Time series и Categoricals можно пропустить.

Оба руководства открываются как ноутбуки: копируйте примеры к себе и меняйте
числа — так быстрее, чем читать подряд.

Библиотеки, которые понадобятся дальше по курсу, описаны на русском:
[scikit-learn.ru](https://scikit-learn.ru/stable/datasets/toy_dataset.html) —
в том числе готовые учебные наборы данных и генераторы выборок.

---

Дальше открывайте `lab01_seminar.ipynb`.